name: orchestrator-agent
description: "Routes requests to specialist agents and aggregates results"
runtime: python3.11
model: gemini-1.5-pro
temperature: 0.2
tools:
  - name: route_to_segmentation
    description: "Route to segmentation agent for client analysis"
  - name: route_to_media
    description: "Route to media fusion agent for headline analysis"
  - name: route_to_nba
    description: "Route to NBA agent for recommendations"
